version: 2

sources:
  - name: sirius
    database: agdf_raw_db
    schema: SIRIUS
    tables:
      - name: brnch
      - name: cstmr
      - name: mjrclnt
      - name: mjrclntdvsn
      - name: schdlbtch
      - name: schdlfrqncy
      - name: schdlitm
      - name: schdlstts
      - name: schdltyp
      - name: srvccd
  - name: checkguard
    database: agdf_raw_db
    schema: checkguard
    tables:
      - name: cntrlshts
      - name: dbt
      - name: dpst
      - name: sndry

  - name: pf_test
    database: agdf_raw_db
    schema: SIRIUS
    tables:
      - name: EXT_BRNCH2
        external:
          location: "@sirius_stage"
          file_format: "PARQUET_FMT"
          columns:
            - name: value
              data_type: variant
